# Generated by Django 4.0.3 on 2022-03-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(default='Migration', max_length=255),
            preserve_default=False,
        ),
    ]
